-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('MoveDTO_pb')


local VECTOR3 = protobuf.Descriptor();
local VECTOR3_X_FIELD = protobuf.FieldDescriptor();
local VECTOR3_Y_FIELD = protobuf.FieldDescriptor();
local VECTOR3_Z_FIELD = protobuf.FieldDescriptor();
local PLAYERDTO = protobuf.Descriptor();
local PLAYERDTO_ID_FIELD = protobuf.FieldDescriptor();
local PLAYERDTO_USERNAME_FIELD = protobuf.FieldDescriptor();
local PLAYSRESULT = protobuf.Descriptor();
local PLAYSRESULT_PLAYES_FIELD = protobuf.FieldDescriptor();
local MOVEDTO = protobuf.Descriptor();
local MOVEDTO_ID_FIELD = protobuf.FieldDescriptor();
local MOVEDTO_POINT_FIELD = protobuf.FieldDescriptor();
local MOVEDTO_ROATION_FIELD = protobuf.FieldDescriptor();
local MOVERESULT = protobuf.Descriptor();
local MOVERESULT_MOVES_FIELD = protobuf.FieldDescriptor();

VECTOR3_X_FIELD.name = "x"
VECTOR3_X_FIELD.full_name = ".msg.Vector3.x"
VECTOR3_X_FIELD.number = 1
VECTOR3_X_FIELD.index = 0
VECTOR3_X_FIELD.label = 1
VECTOR3_X_FIELD.has_default_value = false
VECTOR3_X_FIELD.default_value = ""
VECTOR3_X_FIELD.type = 9
VECTOR3_X_FIELD.cpp_type = 9

VECTOR3_Y_FIELD.name = "y"
VECTOR3_Y_FIELD.full_name = ".msg.Vector3.y"
VECTOR3_Y_FIELD.number = 2
VECTOR3_Y_FIELD.index = 1
VECTOR3_Y_FIELD.label = 1
VECTOR3_Y_FIELD.has_default_value = false
VECTOR3_Y_FIELD.default_value = ""
VECTOR3_Y_FIELD.type = 9
VECTOR3_Y_FIELD.cpp_type = 9

VECTOR3_Z_FIELD.name = "z"
VECTOR3_Z_FIELD.full_name = ".msg.Vector3.z"
VECTOR3_Z_FIELD.number = 3
VECTOR3_Z_FIELD.index = 2
VECTOR3_Z_FIELD.label = 1
VECTOR3_Z_FIELD.has_default_value = false
VECTOR3_Z_FIELD.default_value = ""
VECTOR3_Z_FIELD.type = 9
VECTOR3_Z_FIELD.cpp_type = 9

VECTOR3.name = "Vector3"
VECTOR3.full_name = ".msg.Vector3"
VECTOR3.nested_types = {}
VECTOR3.enum_types = {}
VECTOR3.fields = {VECTOR3_X_FIELD, VECTOR3_Y_FIELD, VECTOR3_Z_FIELD}
VECTOR3.is_extendable = false
VECTOR3.extensions = {}
PLAYERDTO_ID_FIELD.name = "id"
PLAYERDTO_ID_FIELD.full_name = ".msg.PlayerDTO.id"
PLAYERDTO_ID_FIELD.number = 1
PLAYERDTO_ID_FIELD.index = 0
PLAYERDTO_ID_FIELD.label = 1
PLAYERDTO_ID_FIELD.has_default_value = false
PLAYERDTO_ID_FIELD.default_value = 0
PLAYERDTO_ID_FIELD.type = 5
PLAYERDTO_ID_FIELD.cpp_type = 1

PLAYERDTO_USERNAME_FIELD.name = "UserName"
PLAYERDTO_USERNAME_FIELD.full_name = ".msg.PlayerDTO.UserName"
PLAYERDTO_USERNAME_FIELD.number = 2
PLAYERDTO_USERNAME_FIELD.index = 1
PLAYERDTO_USERNAME_FIELD.label = 1
PLAYERDTO_USERNAME_FIELD.has_default_value = false
PLAYERDTO_USERNAME_FIELD.default_value = ""
PLAYERDTO_USERNAME_FIELD.type = 9
PLAYERDTO_USERNAME_FIELD.cpp_type = 9

PLAYERDTO.name = "PlayerDTO"
PLAYERDTO.full_name = ".msg.PlayerDTO"
PLAYERDTO.nested_types = {}
PLAYERDTO.enum_types = {}
PLAYERDTO.fields = {PLAYERDTO_ID_FIELD, PLAYERDTO_USERNAME_FIELD}
PLAYERDTO.is_extendable = false
PLAYERDTO.extensions = {}
PLAYSRESULT_PLAYES_FIELD.name = "playes"
PLAYSRESULT_PLAYES_FIELD.full_name = ".msg.PlaysResult.playes"
PLAYSRESULT_PLAYES_FIELD.number = 1
PLAYSRESULT_PLAYES_FIELD.index = 0
PLAYSRESULT_PLAYES_FIELD.label = 3
PLAYSRESULT_PLAYES_FIELD.has_default_value = false
PLAYSRESULT_PLAYES_FIELD.default_value = {}
PLAYSRESULT_PLAYES_FIELD.message_type = PLAYERDTO
PLAYSRESULT_PLAYES_FIELD.type = 11
PLAYSRESULT_PLAYES_FIELD.cpp_type = 10

PLAYSRESULT.name = "PlaysResult"
PLAYSRESULT.full_name = ".msg.PlaysResult"
PLAYSRESULT.nested_types = {}
PLAYSRESULT.enum_types = {}
PLAYSRESULT.fields = {PLAYSRESULT_PLAYES_FIELD}
PLAYSRESULT.is_extendable = false
PLAYSRESULT.extensions = {}
MOVEDTO_ID_FIELD.name = "id"
MOVEDTO_ID_FIELD.full_name = ".msg.MoveDTO.id"
MOVEDTO_ID_FIELD.number = 1
MOVEDTO_ID_FIELD.index = 0
MOVEDTO_ID_FIELD.label = 1
MOVEDTO_ID_FIELD.has_default_value = false
MOVEDTO_ID_FIELD.default_value = 0
MOVEDTO_ID_FIELD.type = 5
MOVEDTO_ID_FIELD.cpp_type = 1

MOVEDTO_POINT_FIELD.name = "point"
MOVEDTO_POINT_FIELD.full_name = ".msg.MoveDTO.point"
MOVEDTO_POINT_FIELD.number = 2
MOVEDTO_POINT_FIELD.index = 1
MOVEDTO_POINT_FIELD.label = 1
MOVEDTO_POINT_FIELD.has_default_value = false
MOVEDTO_POINT_FIELD.default_value = nil
MOVEDTO_POINT_FIELD.message_type = VECTOR3
MOVEDTO_POINT_FIELD.type = 11
MOVEDTO_POINT_FIELD.cpp_type = 10

MOVEDTO_ROATION_FIELD.name = "roation"
MOVEDTO_ROATION_FIELD.full_name = ".msg.MoveDTO.roation"
MOVEDTO_ROATION_FIELD.number = 3
MOVEDTO_ROATION_FIELD.index = 2
MOVEDTO_ROATION_FIELD.label = 1
MOVEDTO_ROATION_FIELD.has_default_value = false
MOVEDTO_ROATION_FIELD.default_value = nil
MOVEDTO_ROATION_FIELD.message_type = VECTOR3
MOVEDTO_ROATION_FIELD.type = 11
MOVEDTO_ROATION_FIELD.cpp_type = 10

MOVEDTO.name = "MoveDTO"
MOVEDTO.full_name = ".msg.MoveDTO"
MOVEDTO.nested_types = {}
MOVEDTO.enum_types = {}
MOVEDTO.fields = {MOVEDTO_ID_FIELD, MOVEDTO_POINT_FIELD, MOVEDTO_ROATION_FIELD}
MOVEDTO.is_extendable = false
MOVEDTO.extensions = {}
MOVERESULT_MOVES_FIELD.name = "moves"
MOVERESULT_MOVES_FIELD.full_name = ".msg.MoveResult.moves"
MOVERESULT_MOVES_FIELD.number = 1
MOVERESULT_MOVES_FIELD.index = 0
MOVERESULT_MOVES_FIELD.label = 3
MOVERESULT_MOVES_FIELD.has_default_value = false
MOVERESULT_MOVES_FIELD.default_value = {}
MOVERESULT_MOVES_FIELD.message_type = MOVEDTO
MOVERESULT_MOVES_FIELD.type = 11
MOVERESULT_MOVES_FIELD.cpp_type = 10

MOVERESULT.name = "MoveResult"
MOVERESULT.full_name = ".msg.MoveResult"
MOVERESULT.nested_types = {}
MOVERESULT.enum_types = {}
MOVERESULT.fields = {MOVERESULT_MOVES_FIELD}
MOVERESULT.is_extendable = false
MOVERESULT.extensions = {}

MoveDTO = protobuf.Message(MOVEDTO)
MoveResult = protobuf.Message(MOVERESULT)
PlayerDTO = protobuf.Message(PLAYERDTO)
PlaysResult = protobuf.Message(PLAYSRESULT)
Vector3 = protobuf.Message(VECTOR3)

