-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('StatusDTO_pb')


local STATUSDTO = protobuf.Descriptor();
local STATUSDTO_STATUS = protobuf.Descriptor();
local STATUSDTO_STATUS_WA_FIELD = protobuf.FieldDescriptor();
local STATUSDTO_STATUS_WR_FIELD = protobuf.FieldDescriptor();
local STATUSDTO_STATUS_WI_FIELD = protobuf.FieldDescriptor();
local STATUSDTO_STATUS_WJ_FIELD = protobuf.FieldDescriptor();
local STATUSDTO_ID_FIELD = protobuf.FieldDescriptor();
local STATUSDTO_STATUS_FIELD = protobuf.FieldDescriptor();
local STATUSRESULT = protobuf.Descriptor();
local STATUSRESULT_STATUS_FIELD = protobuf.FieldDescriptor();

STATUSDTO_STATUS_WA_FIELD.name = "wa"
STATUSDTO_STATUS_WA_FIELD.full_name = ".msg.StatusDTO.Status.wa"
STATUSDTO_STATUS_WA_FIELD.number = 2
STATUSDTO_STATUS_WA_FIELD.index = 0
STATUSDTO_STATUS_WA_FIELD.label = 1
STATUSDTO_STATUS_WA_FIELD.has_default_value = false
STATUSDTO_STATUS_WA_FIELD.default_value = 0
STATUSDTO_STATUS_WA_FIELD.type = 5
STATUSDTO_STATUS_WA_FIELD.cpp_type = 1

STATUSDTO_STATUS_WR_FIELD.name = "wr"
STATUSDTO_STATUS_WR_FIELD.full_name = ".msg.StatusDTO.Status.wr"
STATUSDTO_STATUS_WR_FIELD.number = 1
STATUSDTO_STATUS_WR_FIELD.index = 1
STATUSDTO_STATUS_WR_FIELD.label = 1
STATUSDTO_STATUS_WR_FIELD.has_default_value = false
STATUSDTO_STATUS_WR_FIELD.default_value = false
STATUSDTO_STATUS_WR_FIELD.type = 8
STATUSDTO_STATUS_WR_FIELD.cpp_type = 7

STATUSDTO_STATUS_WI_FIELD.name = "wi"
STATUSDTO_STATUS_WI_FIELD.full_name = ".msg.StatusDTO.Status.wi"
STATUSDTO_STATUS_WI_FIELD.number = 3
STATUSDTO_STATUS_WI_FIELD.index = 2
STATUSDTO_STATUS_WI_FIELD.label = 1
STATUSDTO_STATUS_WI_FIELD.has_default_value = false
STATUSDTO_STATUS_WI_FIELD.default_value = false
STATUSDTO_STATUS_WI_FIELD.type = 8
STATUSDTO_STATUS_WI_FIELD.cpp_type = 7

STATUSDTO_STATUS_WJ_FIELD.name = "wj"
STATUSDTO_STATUS_WJ_FIELD.full_name = ".msg.StatusDTO.Status.wj"
STATUSDTO_STATUS_WJ_FIELD.number = 4
STATUSDTO_STATUS_WJ_FIELD.index = 3
STATUSDTO_STATUS_WJ_FIELD.label = 1
STATUSDTO_STATUS_WJ_FIELD.has_default_value = false
STATUSDTO_STATUS_WJ_FIELD.default_value = false
STATUSDTO_STATUS_WJ_FIELD.type = 8
STATUSDTO_STATUS_WJ_FIELD.cpp_type = 7

STATUSDTO_STATUS.name = "Status"
STATUSDTO_STATUS.full_name = ".msg.StatusDTO.Status"
STATUSDTO_STATUS.nested_types = {}
STATUSDTO_STATUS.enum_types = {}
STATUSDTO_STATUS.fields = {STATUSDTO_STATUS_WA_FIELD, STATUSDTO_STATUS_WR_FIELD, STATUSDTO_STATUS_WI_FIELD, STATUSDTO_STATUS_WJ_FIELD}
STATUSDTO_STATUS.is_extendable = false
STATUSDTO_STATUS.extensions = {}
STATUSDTO_STATUS.containing_type = STATUSDTO
STATUSDTO_ID_FIELD.name = "id"
STATUSDTO_ID_FIELD.full_name = ".msg.StatusDTO.id"
STATUSDTO_ID_FIELD.number = 1
STATUSDTO_ID_FIELD.index = 0
STATUSDTO_ID_FIELD.label = 1
STATUSDTO_ID_FIELD.has_default_value = false
STATUSDTO_ID_FIELD.default_value = 0
STATUSDTO_ID_FIELD.type = 5
STATUSDTO_ID_FIELD.cpp_type = 1

STATUSDTO_STATUS_FIELD.name = "status"
STATUSDTO_STATUS_FIELD.full_name = ".msg.StatusDTO.status"
STATUSDTO_STATUS_FIELD.number = 2
STATUSDTO_STATUS_FIELD.index = 1
STATUSDTO_STATUS_FIELD.label = 1
STATUSDTO_STATUS_FIELD.has_default_value = false
STATUSDTO_STATUS_FIELD.default_value = nil
STATUSDTO_STATUS_FIELD.message_type = STATUSDTO_STATUS
STATUSDTO_STATUS_FIELD.type = 11
STATUSDTO_STATUS_FIELD.cpp_type = 10

STATUSDTO.name = "StatusDTO"
STATUSDTO.full_name = ".msg.StatusDTO"
STATUSDTO.nested_types = {STATUSDTO_STATUS}
STATUSDTO.enum_types = {}
STATUSDTO.fields = {STATUSDTO_ID_FIELD, STATUSDTO_STATUS_FIELD}
STATUSDTO.is_extendable = false
STATUSDTO.extensions = {}
STATUSRESULT_STATUS_FIELD.name = "status"
STATUSRESULT_STATUS_FIELD.full_name = ".msg.StatusResult.status"
STATUSRESULT_STATUS_FIELD.number = 1
STATUSRESULT_STATUS_FIELD.index = 0
STATUSRESULT_STATUS_FIELD.label = 3
STATUSRESULT_STATUS_FIELD.has_default_value = false
STATUSRESULT_STATUS_FIELD.default_value = {}
STATUSRESULT_STATUS_FIELD.message_type = STATUSDTO
STATUSRESULT_STATUS_FIELD.type = 11
STATUSRESULT_STATUS_FIELD.cpp_type = 10

STATUSRESULT.name = "StatusResult"
STATUSRESULT.full_name = ".msg.StatusResult"
STATUSRESULT.nested_types = {}
STATUSRESULT.enum_types = {}
STATUSRESULT.fields = {STATUSRESULT_STATUS_FIELD}
STATUSRESULT.is_extendable = false
STATUSRESULT.extensions = {}

StatusDTO = protobuf.Message(STATUSDTO)
StatusDTO.Status = protobuf.Message(STATUSDTO_STATUS)
StatusResult = protobuf.Message(STATUSRESULT)

