// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MoveDTO.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vector3 struct {
	X                    string   `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    string   `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    string   `protobuf:"bytes,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector3) Reset()         { *m = Vector3{} }
func (m *Vector3) String() string { return proto.CompactTextString(m) }
func (*Vector3) ProtoMessage()    {}
func (*Vector3) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7b3ac62fbb2e1db, []int{0}
}

func (m *Vector3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector3.Unmarshal(m, b)
}
func (m *Vector3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector3.Marshal(b, m, deterministic)
}
func (m *Vector3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector3.Merge(m, src)
}
func (m *Vector3) XXX_Size() int {
	return xxx_messageInfo_Vector3.Size(m)
}
func (m *Vector3) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector3.DiscardUnknown(m)
}

var xxx_messageInfo_Vector3 proto.InternalMessageInfo

func (m *Vector3) GetX() string {
	if m != nil {
		return m.X
	}
	return ""
}

func (m *Vector3) GetY() string {
	if m != nil {
		return m.Y
	}
	return ""
}

func (m *Vector3) GetZ() string {
	if m != nil {
		return m.Z
	}
	return ""
}

type PlayerDTO struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerDTO) Reset()         { *m = PlayerDTO{} }
func (m *PlayerDTO) String() string { return proto.CompactTextString(m) }
func (*PlayerDTO) ProtoMessage()    {}
func (*PlayerDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7b3ac62fbb2e1db, []int{1}
}

func (m *PlayerDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerDTO.Unmarshal(m, b)
}
func (m *PlayerDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerDTO.Marshal(b, m, deterministic)
}
func (m *PlayerDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerDTO.Merge(m, src)
}
func (m *PlayerDTO) XXX_Size() int {
	return xxx_messageInfo_PlayerDTO.Size(m)
}
func (m *PlayerDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerDTO.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerDTO proto.InternalMessageInfo

func (m *PlayerDTO) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlayerDTO) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type PlaysResult struct {
	Playes               []*PlayerDTO `protobuf:"bytes,1,rep,name=playes,proto3" json:"playes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PlaysResult) Reset()         { *m = PlaysResult{} }
func (m *PlaysResult) String() string { return proto.CompactTextString(m) }
func (*PlaysResult) ProtoMessage()    {}
func (*PlaysResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7b3ac62fbb2e1db, []int{2}
}

func (m *PlaysResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaysResult.Unmarshal(m, b)
}
func (m *PlaysResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaysResult.Marshal(b, m, deterministic)
}
func (m *PlaysResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaysResult.Merge(m, src)
}
func (m *PlaysResult) XXX_Size() int {
	return xxx_messageInfo_PlaysResult.Size(m)
}
func (m *PlaysResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaysResult.DiscardUnknown(m)
}

var xxx_messageInfo_PlaysResult proto.InternalMessageInfo

func (m *PlaysResult) GetPlayes() []*PlayerDTO {
	if m != nil {
		return m.Playes
	}
	return nil
}

type MoveDTO struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Point                *Vector3 `protobuf:"bytes,2,opt,name=point,proto3" json:"point,omitempty"`
	Roation              *Vector3 `protobuf:"bytes,3,opt,name=roation,proto3" json:"roation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveDTO) Reset()         { *m = MoveDTO{} }
func (m *MoveDTO) String() string { return proto.CompactTextString(m) }
func (*MoveDTO) ProtoMessage()    {}
func (*MoveDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7b3ac62fbb2e1db, []int{3}
}

func (m *MoveDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveDTO.Unmarshal(m, b)
}
func (m *MoveDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveDTO.Marshal(b, m, deterministic)
}
func (m *MoveDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveDTO.Merge(m, src)
}
func (m *MoveDTO) XXX_Size() int {
	return xxx_messageInfo_MoveDTO.Size(m)
}
func (m *MoveDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveDTO.DiscardUnknown(m)
}

var xxx_messageInfo_MoveDTO proto.InternalMessageInfo

func (m *MoveDTO) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MoveDTO) GetPoint() *Vector3 {
	if m != nil {
		return m.Point
	}
	return nil
}

func (m *MoveDTO) GetRoation() *Vector3 {
	if m != nil {
		return m.Roation
	}
	return nil
}

type MoveResult struct {
	Moves                []*MoveDTO `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MoveResult) Reset()         { *m = MoveResult{} }
func (m *MoveResult) String() string { return proto.CompactTextString(m) }
func (*MoveResult) ProtoMessage()    {}
func (*MoveResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7b3ac62fbb2e1db, []int{4}
}

func (m *MoveResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveResult.Unmarshal(m, b)
}
func (m *MoveResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveResult.Marshal(b, m, deterministic)
}
func (m *MoveResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveResult.Merge(m, src)
}
func (m *MoveResult) XXX_Size() int {
	return xxx_messageInfo_MoveResult.Size(m)
}
func (m *MoveResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveResult.DiscardUnknown(m)
}

var xxx_messageInfo_MoveResult proto.InternalMessageInfo

func (m *MoveResult) GetMoves() []*MoveDTO {
	if m != nil {
		return m.Moves
	}
	return nil
}

func init() {
	proto.RegisterType((*Vector3)(nil), "msg.Vector3")
	proto.RegisterType((*PlayerDTO)(nil), "msg.PlayerDTO")
	proto.RegisterType((*PlaysResult)(nil), "msg.PlaysResult")
	proto.RegisterType((*MoveDTO)(nil), "msg.MoveDTO")
	proto.RegisterType((*MoveResult)(nil), "msg.MoveResult")
}

func init() { proto.RegisterFile("MoveDTO.proto", fileDescriptor_e7b3ac62fbb2e1db) }

var fileDescriptor_e7b3ac62fbb2e1db = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xbb, 0x6a, 0xc3, 0x30,
	0x14, 0x86, 0x91, 0x8d, 0xe3, 0xe6, 0x38, 0xcd, 0xa0, 0x49, 0x74, 0x0a, 0x1a, 0x42, 0x26, 0x53,
	0x62, 0x4a, 0x5f, 0x20, 0x6b, 0x9b, 0x22, 0xd2, 0xee, 0x6e, 0x23, 0x82, 0x20, 0xca, 0x31, 0x92,
	0x6a, 0x6c, 0x3f, 0x7d, 0xd1, 0xa5, 0x1e, 0xda, 0xf1, 0xe3, 0xd7, 0x7f, 0x39, 0x82, 0xfb, 0x17,
	0xec, 0xe5, 0xe1, 0x74, 0xac, 0x3b, 0x83, 0x0e, 0x69, 0xae, 0xed, 0x85, 0x37, 0x50, 0x7e, 0xc8,
	0x2f, 0x87, 0xa6, 0xa1, 0x2b, 0x20, 0x03, 0x23, 0x1b, 0xb2, 0x5b, 0x0a, 0x32, 0x78, 0x1a, 0x59,
	0x16, 0x69, 0xf4, 0x34, 0xb1, 0x3c, 0xd2, 0xc4, 0x9f, 0x61, 0xf9, 0x76, 0x6d, 0x47, 0x69, 0x0e,
	0xa7, 0x23, 0x5d, 0x43, 0xa6, 0xce, 0xc1, 0x57, 0x88, 0x4c, 0x9d, 0xe9, 0x03, 0xdc, 0xbd, 0x5b,
	0x69, 0x5e, 0x5b, 0x2d, 0x93, 0x7f, 0x66, 0xfe, 0x04, 0x95, 0x37, 0x5a, 0x21, 0xed, 0xf7, 0xd5,
	0xd1, 0x2d, 0x2c, 0x3a, 0x9f, 0x63, 0x19, 0xd9, 0xe4, 0xbb, 0x6a, 0xbf, 0xae, 0xb5, 0xbd, 0xd4,
	0x73, 0xb4, 0x48, 0x2a, 0x97, 0x50, 0xa6, 0xe9, 0xff, 0xda, 0x38, 0x14, 0x1d, 0xaa, 0x9b, 0x0b,
	0x55, 0xd5, 0x7e, 0x15, 0x12, 0xd2, 0x45, 0x22, 0x4a, 0x74, 0x0b, 0xa5, 0xc1, 0xd6, 0x29, 0xbc,
	0x85, 0x13, 0xfe, 0xbe, 0xfa, 0x15, 0xf9, 0x23, 0x80, 0xaf, 0x49, 0xe3, 0x38, 0x14, 0x1a, 0xfb,
	0x79, 0x5b, 0xf4, 0xa4, 0x19, 0x22, 0x4a, 0x9f, 0x8b, 0xf0, 0x93, 0xcd, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xfa, 0xd7, 0x9a, 0xfc, 0x5a, 0x01, 0x00, 0x00,
}
