// Code generated by protoc-gen-go. DO NOT EDIT.
// source: StatusDTO.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusDTO struct {
	Id                   int32             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               *StatusDTO_Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StatusDTO) Reset()         { *m = StatusDTO{} }
func (m *StatusDTO) String() string { return proto.CompactTextString(m) }
func (*StatusDTO) ProtoMessage()    {}
func (*StatusDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_f30cf25d20697fc5, []int{0}
}

func (m *StatusDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusDTO.Unmarshal(m, b)
}
func (m *StatusDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusDTO.Marshal(b, m, deterministic)
}
func (m *StatusDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusDTO.Merge(m, src)
}
func (m *StatusDTO) XXX_Size() int {
	return xxx_messageInfo_StatusDTO.Size(m)
}
func (m *StatusDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusDTO.DiscardUnknown(m)
}

var xxx_messageInfo_StatusDTO proto.InternalMessageInfo

func (m *StatusDTO) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StatusDTO) GetStatus() *StatusDTO_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type StatusDTO_Status struct {
	Wa                   int32    `protobuf:"varint,1,opt,name=wa,proto3" json:"wa,omitempty"`
	Wr                   int32    `protobuf:"varint,2,opt,name=wr,proto3" json:"wr,omitempty"`
	Wi                   int32    `protobuf:"varint,3,opt,name=wi,proto3" json:"wi,omitempty"`
	Wj                   int32    `protobuf:"varint,4,opt,name=wj,proto3" json:"wj,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusDTO_Status) Reset()         { *m = StatusDTO_Status{} }
func (m *StatusDTO_Status) String() string { return proto.CompactTextString(m) }
func (*StatusDTO_Status) ProtoMessage()    {}
func (*StatusDTO_Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_f30cf25d20697fc5, []int{0, 0}
}

func (m *StatusDTO_Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusDTO_Status.Unmarshal(m, b)
}
func (m *StatusDTO_Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusDTO_Status.Marshal(b, m, deterministic)
}
func (m *StatusDTO_Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusDTO_Status.Merge(m, src)
}
func (m *StatusDTO_Status) XXX_Size() int {
	return xxx_messageInfo_StatusDTO_Status.Size(m)
}
func (m *StatusDTO_Status) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusDTO_Status.DiscardUnknown(m)
}

var xxx_messageInfo_StatusDTO_Status proto.InternalMessageInfo

func (m *StatusDTO_Status) GetWa() int32 {
	if m != nil {
		return m.Wa
	}
	return 0
}

func (m *StatusDTO_Status) GetWr() int32 {
	if m != nil {
		return m.Wr
	}
	return 0
}

func (m *StatusDTO_Status) GetWi() int32 {
	if m != nil {
		return m.Wi
	}
	return 0
}

func (m *StatusDTO_Status) GetWj() int32 {
	if m != nil {
		return m.Wj
	}
	return 0
}

type StatusResult struct {
	Status               []*StatusDTO `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StatusResult) Reset()         { *m = StatusResult{} }
func (m *StatusResult) String() string { return proto.CompactTextString(m) }
func (*StatusResult) ProtoMessage()    {}
func (*StatusResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_f30cf25d20697fc5, []int{1}
}

func (m *StatusResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResult.Unmarshal(m, b)
}
func (m *StatusResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResult.Marshal(b, m, deterministic)
}
func (m *StatusResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResult.Merge(m, src)
}
func (m *StatusResult) XXX_Size() int {
	return xxx_messageInfo_StatusResult.Size(m)
}
func (m *StatusResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResult.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResult proto.InternalMessageInfo

func (m *StatusResult) GetStatus() []*StatusDTO {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*StatusDTO)(nil), "msg.StatusDTO")
	proto.RegisterType((*StatusDTO_Status)(nil), "msg.StatusDTO.Status")
	proto.RegisterType((*StatusResult)(nil), "msg.StatusResult")
}

func init() { proto.RegisterFile("StatusDTO.proto", fileDescriptor_f30cf25d20697fc5) }

var fileDescriptor_f30cf25d20697fc5 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0f, 0x2e, 0x49, 0x2c,
	0x29, 0x2d, 0x76, 0x09, 0xf1, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e,
	0x57, 0x9a, 0xc2, 0xc8, 0xc5, 0x09, 0x97, 0x10, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54,
	0x60, 0xd4, 0x60, 0x0d, 0x62, 0xca, 0x4c, 0x11, 0xd2, 0xe5, 0x62, 0x2b, 0x06, 0x4b, 0x4a, 0x30,
	0x29, 0x30, 0x6a, 0x70, 0x1b, 0x89, 0xea, 0xe5, 0x16, 0xa7, 0xeb, 0x21, 0x0c, 0x82, 0xb0, 0x82,
	0xa0, 0x8a, 0xa4, 0x3c, 0xb8, 0xd8, 0x20, 0x22, 0x20, 0x83, 0xca, 0x13, 0x61, 0x06, 0x95, 0x27,
	0x82, 0xf9, 0x45, 0x60, 0x43, 0x40, 0xfc, 0x22, 0x30, 0x3f, 0x53, 0x82, 0x19, 0xca, 0xcf, 0x04,
	0xf3, 0xb3, 0x24, 0x58, 0xa0, 0xfc, 0x2c, 0x25, 0x33, 0x2e, 0x1e, 0xa8, 0xd9, 0xa9, 0xc5, 0xa5,
	0x39, 0x25, 0x42, 0x6a, 0x70, 0x87, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0xf1, 0xa1, 0x3a, 0x04,
	0xe6, 0x82, 0x24, 0x36, 0xb0, 0xd7, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x3b, 0xb4,
	0x0e, 0xed, 0x00, 0x00, 0x00,
}
